spring:
  datasource:
    url: "${BABYGUESS_DATABASE_URL:jdbc:h2:file:./data/babyguess;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}"
    username: "${BABYGUESS_DATABASE_USERNAME:sa}"
    password: "${BABYGUESS_DATABASE_PASSWORD:}"
  thymeleaf:
    cache: true

server:
  servlet:
    session:
      cookie:
        secure: "${BABYGUESS_SECURE_COOKIES:true}"
