CREATE TABLE event_configuration (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    title VARCHAR(160) NOT NULL,
    submission_deadline TIMESTAMP WITH TIME ZONE,
    event_timezone VARCHAR(80) NOT NULL DEFAULT 'Europe/Zurich',
    maximum_name_guesses INTEGER NOT NULL DEFAULT 3 CHECK (maximum_name_guesses >= 1),
    ranked_name_scoring BOOLEAN NOT NULL DEFAULT TRUE,
    name_weight DECIMAL(19, 8) NOT NULL DEFAULT 1 CHECK (name_weight >= 0),
    sex_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    sex_weight DECIMAL(19, 8) NOT NULL DEFAULT 1 CHECK (sex_weight >= 0),
    birth_date_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    birth_date_weight DECIMAL(19, 8) NOT NULL DEFAULT 1 CHECK (birth_date_weight >= 0),
    birth_date_tolerance_days INTEGER NOT NULL DEFAULT 5 CHECK (birth_date_tolerance_days >= 0),
    birth_weight_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    birth_weight_weight DECIMAL(19, 8) NOT NULL DEFAULT 1 CHECK (birth_weight_weight >= 0),
    birth_weight_tolerance_grams INTEGER NOT NULL DEFAULT 500 CHECK (birth_weight_tolerance_grams >= 0),
    logo_asset_name VARCHAR(255),
    background_asset_name VARCHAR(255),
    actual_name VARCHAR(160),
    actual_sex VARCHAR(16) CHECK (actual_sex IN ('GIRL', 'BOY')),
    actual_birth_date DATE,
    actual_birth_weight_grams INTEGER CHECK (actual_birth_weight_grams > 0),
    revealed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO event_configuration (id, title, updated_at)
VALUES (1, 'BabyGuess', CURRENT_TIMESTAMP);

CREATE TABLE participant (
    id UUID PRIMARY KEY,
    display_name VARCHAR(120) NOT NULL,
    email_address VARCHAR(320) NOT NULL,
    normalized_email_address VARCHAR(320) NOT NULL UNIQUE,
    edit_token_hash CHAR(64) NOT NULL UNIQUE,
    locale VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE submission_version (
    id UUID PRIMARY KEY,
    participant_id UUID NOT NULL REFERENCES participant(id),
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    predicted_sex VARCHAR(16) CHECK (predicted_sex IN ('GIRL', 'BOY')),
    predicted_birth_date DATE,
    predicted_birth_weight_grams INTEGER CHECK (predicted_birth_weight_grams > 0)
);

CREATE INDEX submission_version_participant_time_idx
    ON submission_version (participant_id, submitted_at DESC);

CREATE TABLE name_guess (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_version_id UUID NOT NULL REFERENCES submission_version(id),
    guess_position INTEGER NOT NULL CHECK (guess_position >= 1),
    guessed_name VARCHAR(160) NOT NULL,
    cosmetic_name VARCHAR(160) NOT NULL,
    UNIQUE (submission_version_id, guess_position),
    UNIQUE (submission_version_id, cosmetic_name)
);

CREATE TABLE accepted_name_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cosmetic_name VARCHAR(160) NOT NULL UNIQUE,
    display_name VARCHAR(160) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
