CREATE TABLE name_match_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actual_cosmetic_name VARCHAR(160) NOT NULL,
    guessed_cosmetic_name VARCHAR(160) NOT NULL,
    guessed_display_name VARCHAR(160) NOT NULL,
    decision VARCHAR(16) NOT NULL CHECK (decision IN ('ACCEPTED', 'REJECTED')),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (actual_cosmetic_name, guessed_cosmetic_name)
);

CREATE INDEX name_match_decision_actual_idx
    ON name_match_decision (actual_cosmetic_name);
